export { openDatabase } from './connection.js';
export type { DbHandle, DbOptions } from './connection.js';
export { migrate, SCHEMA_VERSION } from './schema.js';
export { createNovelRepository } from './repositories/novels.js';
export type { NovelRepository } from './repositories/novels.js';
export { createAssetRepository } from './repositories/assets.js';
export type { AssetRepository } from './repositories/assets.js';
export { createOutlineRepository } from './repositories/outline.js';
export type { OutlineRepository } from './repositories/outline.js';
export { createResearchRepository } from './repositories/research.js';
export type { ResearchRepository } from './repositories/research.js';
