export { openDatabase } from './connection.js';
export type { DbHandle, DbOptions } from './connection.js';
export { migrate, SCHEMA_VERSION } from './schema.js';
export { createNovelRepository } from './repositories/novels.js';
export type { NovelRepository } from './repositories/novels.js';
export { createAssetRepository } from './repositories/assets.js';
export type { AssetRepository } from './repositories/assets.js';
export { createOutlineRepository } from './repositories/outline.js';
export type { OutlineRepository } from './repositories/outline.js';
export { createResearchRepository } from './repositories/research.js';
export type { ResearchRepository } from './repositories/research.js';
export { createSceneRepository } from './repositories/scenes.js';
export type { SceneRepository } from './repositories/scenes.js';
export { createSummaryRepository } from './repositories/summaries.js';
export type { SummaryRepository } from './repositories/summaries.js';
export { createFactCardRepository } from './repositories/facts.js';
export type { FactCardRepository } from './repositories/facts.js';
export { createConflictRepository } from './repositories/conflicts.js';
export type { ConflictRepository } from './repositories/conflicts.js';
export { createPlotDeviceRepository } from './repositories/plotdevices.js';
export type { PlotDeviceRepository } from './repositories/plotdevices.js';
export { createChunkRepository } from './repositories/chunks.js';
export type { ChunkRepository, VecHit } from './repositories/chunks.js';
