// 前端类型转发：统一从共享类型导入
export type {
  Novel,
  Asset,
  AssetState,
  AssetInput,
  AssetWriteBack,
  AssetType,
  OutlineNode,
  OutlineNodeInput,
  OutlineLevel,
  OutlineStatus,
  OutlineLayer,
  GenerateOutlineRequest,
  CoreIdea,
  WorldviewItem,
  CharacterBio,
  Synopsis,
  VolumeOutlineItem,
  ChapterOutlineItem,
  SceneOutline,
  SceneMeta,
  Scene,
  SceneStatus,
  FactCard,
  Summary,
  ContentChunk,
  Conflict,
  PlotDevice,
  ResearchReport,
  TrendResearch,
  HealthInfo,
} from '@shared/index';
